admin_tasks/urls.py
from django.urls import path, re_path
from . import views

app_name = "admin_tasks"
urlpatterns = [
    path('', views.index, name="index"),
    path("register-model/", views.register_model, name="register_model"),
    path("delete-model-<model_name>/", views.delete_model),
    path("list-models/model-<model_name>/", views.update_model, name="update_model"),
    path("list-models/", views.list_models, name="list_models"),
    path("list-file-groups/", views.list_file_groups, name="list_file_groups"),
    path("list-file-groups/file-group-<group_name>/", views.update_file_group, name="update_file_group"),
    path("register-data-processing-node/", views.register_data_processing_node, name="register_data_processing_node"),
    path("delete-data-processing-node-<host_user>/", views.delete_data_processing_node,
         name="delete_data_processing_node"),
    path("list-data-processing-nodes/", views.list_data_processing_nodes, name="list_data_processing_nodes"),
    path("list-data-processing-nodes/data-processing-node-<host_user>/", views.update_data_processing_node,
         name="update_data_processing_node"),
    path("load_corpus/", views.load_corpus, name="load_corpus"),
    path("list_artictles/", views.list_articles, name="list_articles"),
    path("list_articles/article-<article_identifier>", views.update_article, name="update_article"),
    path("delete_article-<article_identifier>/", views.delete_article, name="delete_article"),
    path("add_comparison/", views.add_comparison, name="add_comparison"),
    path("list_comparisons/", views.list_comparisons, name="list_comparisons"),
    path("list_comparisons/<comparison_name>", views.update_comparison, name="update_comparison"),
    path("delete-comparison-<comparison_name>/", views.delete_comparison, name="delete_comparison"),
    path("ajax/active-tasks/", views.ajax_polling_task_progress, name="poll_active_tasks"),
    path("ajax/check-model-name-availability/", views.ajax_ensure_unique_model_name,
         name="check_model_name_availability"),
    path("sftp-resources-withdrawal/", views.sftp_resource_withdrawal, name="sftp_resources_withdrawal")

    # TODO: can we make something smart that fills the links of each page
    # re_path(r'a\d',views.index),
    # re_path(r'([.]\/)*',views.index)
]

thesis_django/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from thesis_ui import urls as thesis_ui_urls
from admin_tasks import urls as admin_tasks_urls

urlpatterns = [
    path('', include(thesis_ui_urls)),
    # path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path("admin-tasks/", include(admin_tasks_urls)),
    path('admin/', admin.site.urls),
]

thesis_ui/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path("search-articles/", views.search_articles, name="search_articles"),
    path("topics/article-<article_id>/", views.topic_analysis),
    path("topics/article-<article_id>/ajax/document-topics/", views.ajax_article_topics),
    path("topics/topic-<topic_index>/ajax/topic-evolution/", views.ajax_topic_evolution),
    path("topics/topic-<topic_index>/ajax/topic-terms/", views.ajax_get_topic_terms),
    path("topics/topic-<topic_index>/", views.topic_show),
    path("new-article/", views.new_article_topic_analysis, name="text_topics"),
    path("new-article/ajax/text-topics/", views.ajax_text_topics),
    path('', views.home, name="home"),
    # TODO: can we make something smart that fills the links of each page
    # re_path(r'a\d',views.index),
    # re_path(r'([.]\/)*',views.index)
]

admin_tasks/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Create your models here.

class DataProcessingNode(models.Model):
    host = models.GenericIPAddressField(protocol="IPv4", unique=True)
    username = models.CharField(max_length=32)
    withdrawal_directory = models.CharField(max_length=512)

    def __str__(self):
        return self.username + "@" + self.host


class FileGroup(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=64)

    def __str__(self):
        return str(self.name)


class FileExtension(models.Model):
    extension = models.CharField(max_length=32)
    file_group = models.ForeignKey(FileGroup, on_delete=models.CASCADE)

    def __str__(self):
        return "." + self.extension + " - " + self.file_group.name

admin_tasks/views.py
import os

from django.contrib.admin.views.decorators import staff_member_required
from django.core.cache import cache
from django.db import IntegrityError, DataError
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.text import slugify
from django_celery_results.models import TaskResult

from admin_tasks import forms as atforms
from admin_tasks import functions
from admin_tasks import models as atmodels
from admin_tasks import tasks
from admin_tasks.celery import app as app_worker
from admin_tasks.management.commands import lda_model, data_processing_node, file_group
from thesis_ui import models as thesis_models

inspector = app_worker.control.inspect()


# Create your views here.

@staff_member_required
def index(request):
    # result = fetch_src_files.delay("83.212.72.179", "deligiannis", "Z09!@mPQAL", "/mnt/vdb/data",
    #                                "native_nstemmed.dict")
    return render(request, 'admin_tasks/tasks_map.html')


def ajax_polling_task_progress(request):
    if request.user.is_staff:
        if request.method == "POST":
            referenced_task_id = request.POST.get("task_id", None)
            if referenced_task_id == "":
                referenced_task_id = None
            active_task = cache.get("active_admin_task", None)

            worker_status = "IDLE"
            referenced_task_result = None
            new_task_result = None

            if not referenced_task_id:
                if active_task:
                    new_task_result = {
                        "task_id": active_task["task_id"],
                        "progress": active_task["progress"],
                        "status": active_task["status"],
                        "task_description": active_task["task_description"],
                        "progress_description": active_task["progress_description"]
                    }
                    worker_status = "RUNNING"
            else:
                if not active_task:
                    try:
                        referenced_task_result = functions.fetch_task(referenced_task_id)
                        worker_status = "IDLE"
                    except TaskResult.DoesNotExist:
                        pass
                else:
                    worker_status = "RUNNING"
                    if active_task["task_id"] == referenced_task_id:
                        referenced_task_result = {
                            "task_id": active_task["task_id"],
                            "progress": active_task["progress"],
                            "status": active_task["status"],
                            "task_description": active_task["task_description"],
                            "progress_description": active_task["progress_description"]
                        }
                    else:
                        try:
                            referenced_task_result = functions.fetch_task(referenced_task_id)
                        except TaskResult.DoesNotExist:
                            pass
                        new_task_result = {
                            "task_id": active_task["task_id"],
                            "progress": active_task["progress"],
                            "status": active_task["status"],
                            "task_description": active_task["task_description"],
                            "progress_description": active_task["progress_description"]
                        }
            return JsonResponse({
                "worker_status": worker_status,
                "referenced_task": referenced_task_result,
                "new_task": new_task_result
            })


def ajax_ensure_unique_model_name(request):
    if request.user.is_staff:
        if request.method == "POST":
            model_name = request.POST.get("model_name", None)
            if model_name is not None:
                try:
                    thesis_models.LdaModel.objects.get(name=model_name)
                except thesis_models.LdaModel.DoesNotExist:
                    return JsonResponse({"model_name": model_name, "availability": "AVAILABLE"})
                return JsonResponse({"model_name": model_name, "availability": "UNAVAILABLE"})


# ==================================================================================================================== #
# ==================================================================================================================== #
# ==================================================================================================================== #

@staff_member_required
def register_model(request):
    template_context = dict()
    template_context["path_links"] = [
        {"url": "/admin-tasks", "label": "Admin tasks"},
        {"label": "Register model"}
    ]
    if request.method == "GET":
        task_form = atforms.LdaModelForm()
    else:
        task_form = atforms.LdaModelForm(request.POST)
        if task_form.is_valid():
            active_task = cache.get("active_admin_task", None)
            if active_task is None:
                new_model_name = slugify(task_form.cleaned_data["name"])
                path = task_form.cleaned_data["path"]
                if thesis_models.LdaModel.objects.filter(name=new_model_name).exists():
                    task_form.add_error("name",
                                        "Another LDA model with named as \"{}\" already exists".format(new_model_name))
                elif thesis_models.LdaModel.objects.filter(path=path).exists():
                    task_form.add_error("path",
                                        "Another LDA model that points to the model file at \"{}\" already "
                                        "exists".format(path))
                else:
                    description = task_form.cleaned_data["description"]
                    training_context = task_form.cleaned_data["training_context"]
                    topn = task_form.cleaned_data["top_N_terms"]
                    is_main = task_form.cleaned_data["is_main"]
                    preprocessor_name = task_form.cleaned_data["preprocessor_name"]
                    use_tfidf = task_form.cleaned_data["use_tfidf"]
                    tasks.create_model.delay(new_model_name, path, description, training_context, is_main, topn,
                                             preprocessor_name, use_tfidf)
                    return redirect("/admin-tasks/list-models/")
            else:
                template_context["form_error"] = "New model cannot be registered because another task is currently " \
                                                 "active"
    template_context["task_form"] = task_form
    template_context["form_heading"] = "Register a model"
    return render(request, 'admin_tasks/task_form.html', context=template_context)


@staff_member_required
def list_models(request):
    models = thesis_models.LdaModel.objects.all()
    template_context = dict()
    template_context["path_links"] = [
        {"url": "/admin-tasks", "label": "Admin tasks"},
        {"label": "List models"}
    ]
    template_context["obj"] = {
        "headings": ["Loaded LDA models"],
        "data": [
            {
                "label": str(model) + "@{}".format(model.path),
                "url": "model-" + model.name + "/",
                "name": model.name
            } for model in models
        ],
        "delete_link_prefix": "delete-model-"
    }
    return render(request, 'admin_tasks/db_object_listing.html', context=template_context)


@staff_member_required
def update_model(request, *args, **kwargs):
    model_name = kwargs.get("model_name", None)
    if model_name is not None:
        template_context = dict()
        template_context["path_links"] = [
            {"url": "/admin-tasks", "label": "Admin tasks"},
            {"url": "/admin-tasks/list-models", "label": "List models"},
            {"label": "Update model"}
        ]
        try:
            target_model = thesis_models.LdaModel.objects.get(name=model_name)
        except thesis_models.LdaModel.DoesNotExist as dne:
            return redirect("/admin-tasks/list-models/")
        if request.method == "GET":
            task_form = atforms.LdaModelForm(initial={
                "name": target_model.name,
                "description": target_model.description,
                "training_context": target_model.training_context,
                "is_main": target_model.is_main,
                "preprocessor_name": target_model.preprocessor_name,
                "use_tfidf": target_model.use_tfidf
            }, update=True)
            template_context["task_form"] = task_form
        else:
            task_form = atforms.LdaModelForm(request.POST, update=True)
            backend_error = False
            if task_form.is_valid():
                new_name = task_form.cleaned_data["name"] \
                    if task_form.cleaned_data["name"] != target_model.name else None
                description = task_form.cleaned_data["description"] \
                    if task_form.cleaned_data["description"] != target_model.description else None
                training_context = task_form.cleaned_data["training_context"] \
                    if task_form.cleaned_data["training_context"] != target_model.training_context else None
                set_main = task_form.cleaned_data["is_main"] \
                    if task_form.cleaned_data["is_main"] != target_model.is_main else None
                preprocessor_name = task_form.cleaned_data["preprocessor_name"] \
                    if task_form.cleaned_data["preprocessor_name"] != target_model.preprocessor_name else None
                use_tfidf = task_form.cleaned_data["use_tfidf"] \
                    if task_form.cleaned_data["use_tfidf"] != target_model.use_tfidf else None
                template_context["task_form"] = task_form
                try:

templates/admin_tasks/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin tasks</title>
    {% include 'init_bootstrap.html' %}
    {% include 'init_js.html' %}
    {% include 'init_css.html' %}
</head>
<body>

{% include 'admin_tasks/nav.html' %}

<div class="container">

    <div class="row">
        <div class="col-12">
            <div class="card" id="task-card">
                <div class="card-header" id="task-header">
                    Current task running progress
                </div>
                <div class="card-body" id="task-container">
                    <span class="d-none" id="no-active-task-prompt">No task currently active</span>
                </div>
            </div>
        </div>
    </div>

    <hr>
    {% if path_links %}
        <div>
        {% for link in path_links %}
            {% if not forloop.last %}
                <a href="{{ link.url }}">{{ link.label }}</a>>
            {% else %}
                {{ link.label }}
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>
{% block content_script %}
{% endblock %}
<script>
    let checkForActiveTask = function (task_id = "") {
        $.ajax("{% url "admin_tasks:poll_active_tasks" %}",
            {
                data: {
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    task_id: task_id
                },
                method: "POST",
                success: function (data, status, jqXHR) {
                    {#console.log(data);#}
                    manager.register(data);
                },
                error: function () {
                },
                complete: function (jqXHR, textStatus) {
                    setTimeout(function () {
                        checkForActiveTask(task_id = manager.currentlyActiveTaskId);
                    }, 4000);
                }
            }
        );
    };

    let manager = {

        currentlyActiveTaskId: "",
        tasksStatus: {},

        register: function (ajaxResponse) {
            if (ajaxResponse.referenced_task !== null) {
                if (ajaxResponse.referenced_task.status === "SUCCESS") {
                    this.successful(ajaxResponse.referenced_task);
                    this.currentlyActiveTaskId=""
                } else if (ajaxResponse.referenced_task.status === "FAILURE") {
                    this.failed(ajaxResponse.referenced_task);
                    this.currentlyActiveTaskId=""
                } else if (ajaxResponse.referenced_task.status === "RUNNING") {
                    this.tasksStatus[ajaxResponse.referenced_task.task_id] = 5;
                    this.update(ajaxResponse.referenced_task);
                    this.currentlyActiveTaskId = ajaxResponse.referenced_task.task_id;
                }
            }
            if (ajaxResponse.new_task !== null) {
                this.currentlyActiveTaskId = ajaxResponse.new_task.task_id;
                this.create(ajaxResponse.new_task);
                this.update(ajaxResponse.new_task);
                this.tasksStatus[this.currentlyActiveTaskId] = 5;

                document.getElementById("no-active-task-prompt").classList = ["d-none"];
                document.getElementById("no-active-task-prompt").className = "d-none";
            }

            for (let taskId in this.tasksStatus) {
                if (this.tasksStatus[taskId] > 0) {
                    this.tasksStatus[taskId]--;
                } else {
                    let deadTask = document.getElementById("task-" + taskId);
                    delete this.tasksStatus[taskId];
                    $(deadTask).alert("close");
                }
            }
            if (jQuery.isEmptyObject(this.tasksStatus)) {
                document.getElementById("no-active-task-prompt").removeAttribute("class")
            }
        },

        successful: function (task) {
            let taskId = task.task_id;
            let taskDiv = document.getElementById("task-" + taskId);
            if (taskDiv !== null) {
                taskDiv.classList.replace("alert-dark", "alert-success");
                taskDiv.className.replace("alert-dark", "alert-success");
            }
            let taskProgressBar = document.getElementById("task-" + taskId + "-progress-bar");
            if (taskProgressBar !== null) {
                taskProgressBar.classList.replace("bg-dark", "bg-success");
                taskProgressBar.className.replace("bg-dark", "bg-success");
                taskProgressBar.setAttribute("aria-valuenow", "100");
                taskProgressBar.style.width = "100%";
            }

            let taskHeader = document.getElementById("task-" + taskId + "-header");
            taskHeader.innerText = task.task_description;

            let taskDescription = document.getElementById("task-" + taskId + "-description");
            taskDescription.innerText = task.progress_description;
        },

        failed: function (task) {
            let taskId = task.task_id;
            let taskDiv = document.getElementById("task-" + taskId);
            if (taskDiv !== null) {
                taskDiv.classList.replace("alert-dark", "alert-danger");
                taskDiv.className.replace("alert-dark", "alert-danger");
            }
            let taskProgressBar = document.getElementById("task-" + taskId + "-progress-bar");
            if (taskProgressBar !== null) {
                taskProgressBar.classList.replace("bg-dark", "bg-danger");
                taskProgressBar.className.replace("bg-dark", "bg-danger");
                taskProgressBar.setAttribute("aria-valuenow", "100");
                taskProgressBar.style.width = "100%";
            }

            let taskHeader = document.getElementById("task-" + taskId + "-header");
            taskHeader.innerText = task.task_description;

            let taskDescription = document.getElementById("task-" + taskId + "-description");
            taskDescription.innerText = task.progress_description;
        },

        update: function (task) {
            let taskId = task.task_id;
            let progress = task.progress;
            let taskProgressBar = document.getElementById("task-" + taskId + "-progress-bar");
            taskProgressBar.setAttribute("aria-valuenow", "" + progress);
            taskProgressBar.style.width = "" + progress + "%";

            let taskHeader = document.getElementById("task-" + taskId + "-header");
            taskHeader.innerText = task.task_description;

            let taskDescription = document.getElementById("task-" + taskId + "-description");
            taskDescription.innerText = task.progress_description;
        },

        create: function (task) {
            let taskId = task.task_id;

            let progressBar = document.createElement("div");
            progressBar.setAttribute("id", "task-" + taskId + "-progress-bar");
            progressBar.setAttribute("role", "progressbar");
            progressBar.setAttribute("aria-valuenow", "0");
            progressBar.setAttribute("aria-valuemin", "0");
            progressBar.setAttribute("aria-valuemax", "100");
            progressBar.style.width = "0%";
            progressBar.className = "progress-bar bg-dark";
            progressBar.classList.add("progress-bar", "bg-dark");

            let progressContainer = document.createElement("div");
            progressContainer.className = "progress task-progress-bar-container";
            progressContainer.classList.add("progress", "task-progress-bar-container");

            let progressDescription = document.createElement("span");
            progressDescription.setAttribute("id", "task-" + taskId + "-description");
            let progressDescriptionParagraph = document.createElement("p");

            let progressHeader = document.createElement("h5");
            progressHeader.setAttribute("id", "task-" + taskId + "-header");
            progressHeader.className = "alert-heading";
            progressHeader.classList.add("alert-heading");

            let taskAlert = document.createElement("div");
            taskAlert.setAttribute("id", "task-" + taskId);
            taskAlert.setAttribute("role", "alert");
            taskAlert.className = "alert alert-dark fade show";
            taskAlert.classList.add("alert", "alert-dark", "fade", "show");

            progressContainer.appendChild(progressBar);
            progressDescriptionParagraph.appendChild(progressDescription);
            taskAlert.appendChild(progressHeader);
            taskAlert.appendChild(progressDescriptionParagraph);
            taskAlert.appendChild(progressContainer);
            document.getElementById("task-container").appendChild(taskAlert);
        },
    };

    checkForActiveTask();

    {% if alert %}
        window.onload = function() {
            alert("{{ alert.alert_message }}")
        };
    {% endif %}
</script>
</body>
</html>

templates/admin_tasks/nav.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_tasks:index' %}"><span class="sr-only">(current)</span>Admin tasks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Administration main site</a>
                </li>
{#                {% for link in navbar %}#}
{#                    {% if 'children' in link %}#}
{#                        <li class="nav-item dropdown">#}
{#                            <a class="nav-link{% if link.active %} active{% endif %} dropdown-toggle" href="#"#}
{#                               id="{{ link.name }}" role="button" data-toggle="dropdown" aria-haspopup="true"#}
{#                               aria-expanded="false">{{ link.label }}</a>#}
{#                            <ul class="dropdown-menu bg-dark" aria-labelledby="{{ link.name }}">#}
{#                                {% for child in link.children %}#}
{#                                    <li><a class="dropdown-item{% if child.active %} active{% endif %}"#}
{#                                           href="{{ child.url }}" id="{{ child.name }}">#}
{#                                        {{ child.label }}{% if child.active %}#}
{#                                            <span class="sr-only">(current)</span>{% endif %}</a></li>#}
{#                                {% endfor %}#}
{#                            </ul>#}
{#                        </li>#}
{#                    {% else %}#}
{#                        <li class="nav-item">#}
{#                            <a class="nav-link{% if link.active %} active{% endif %}" href="{{ link.url }}"#}
{#                               id="{{ link.name }}">{{ link.label }}{% if child.active %}#}
{#                                <span class="sr-only">(current)</span>{% endif %}</a>#}
{#                        </li>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
            </ul>
        </div>
    </div>
</nav>

templates/admin_tasks/task_form.html
{% extends "admin_tasks/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row my-4">
        <div class="col-12">
            <h4>{{ form_heading }}</h4>
            {% if form_error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <h5>An error occurred</h5>
                    {{ form_error }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
            <form name="task-form" action="" method="post">
                {% crispy task_form task_form.helper %}
            </form>
        </div>
    </div>
{% endblock %}

templates/admin_tasks/tasks_map.html
{% extends "admin_tasks/base.html" %}

{% block content %}
    <h2>Application data actions</h2>
    <ul>
        <p>
            <li>
                <h4>LDA Model</h4>
                <a href="{% url "admin_tasks:register_model" %}" class="btn btn-primary">Register a model</a>
                <a href="{% url 'admin_tasks:list_models' %}" class="btn btn-warning">List models</a>
            </li>
        </p>
    </ul>
    <ul>
        <p>
            <li>
                <h4>Articles</h4>
                <a href="#" class="btn btn-secondary">Loaded corpus</a>
            </li>
        </p>
        <p>
            <li>
                <h4>Article topics</h4>
                <a href="#" class="btn btn-secondary">Corpus articles' topics</a>
            </li>
        </p>
        <p>
            <li>
                <h4>Pre-stemmed words</h4>
                <a href="#" class="btn btn-secondary">Set pre-stemmed words dictionary</a>
            </li>
        </p>
        <p>
            <li>
                <h4>Topic keyphrases</h4>
                <a href="#" class="btn btn-secondary">Assign keyphrases to model</a>
            </li>
        </p>
    </ul>
    <ul>
        <p>
            <li>
                <h4>Model Comparisons</h4>
                <a href="{% url "admin_tasks:add_comparison" %}" class="btn btn-primary">Add a comparison</a>
                <a href="{% url 'admin_tasks:list_comparisons' %}" class="btn btn-warning">List comparisons</a>
    </li>
        </p>
    </ul>
    <hr>
    <h2>Administration data actions</h2>
    <ul>
        <p>
        <li>
            <h4>Data Processing Nodes</h4>
            <a href="{% url "admin_tasks:register_data_processing_node" %}" class="btn btn-primary">Register a data processing node</a>
                <a href="{% url 'admin_tasks:list_data_processing_nodes' %}" class="btn btn-warning">List data processing nodes</a>
            </li>
        </p>
        <p>
            <li>
                <h4>File Groups</h4>
                <a href="{% url 'admin_tasks:list_file_groups' %}" class="btn btn-warning">List file groups</a>
            </li>
        </p>
        <p>
            <li>
                <h4>SFTP Resource Withdrawal</h4>
                <a href="{% url "admin_tasks:sftp_resources_withdrawal" %}" class="btn btn-primary">Withdraw resource files</a>
            </li>
        </p>
    </ul>
{% endblock %}